'use client';

import { useCallback, useEffect, useState } from 'react';
import { Button } from '@/components/ui/Button';
import {
  cacheNarration,
  getCachedNarration,
} from '@/lib/video-explanation';
import { useListenButtonsPreference } from '@/hooks/useListenButtonsPreference';
import { useReadAlongPlayback } from '@/hooks/useReadAlongPlayback';
import { ReadAlongSentences } from '@/components/audio/ReadAlongSentences';
import { cancelActiveTtsPlayback } from '@/lib/tts-client';

interface NarrationPanelProps {
  challengeId: string;
  challengeType?: 'builtin' | 'user';
}

export function NarrationPanel({
  challengeId,
  challengeType = 'builtin',
}: NarrationPanelProps) {
  const [script, setScript] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState(false);
  const { highlightWhileReading } = useListenButtonsPreference();
  const playback = useReadAlongPlayback(script ?? '');

  const loadScript = useCallback(async () => {
    const cached = getCachedNarration(challengeId);
    if (cached) {
      setScript(cached);
      setExpanded(true);
      return cached;
    }

    setIsLoading(true);
    setError(null);

    try {
      const res = await fetch('/api/ai/narration', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ challengeId, challengeType }),
      });

      if (!res.ok) {
        throw new Error('Failed to generate narration');
      }

      const data = (await res.json()) as { script: string };
      setScript(data.script);
      cacheNarration(challengeId, data.script);
      setExpanded(true);
      return data.script;
    } catch {
      setError('Could not generate narration. Please try again.');
      return null;
    } finally {
      setIsLoading(false);
    }
  }, [challengeId, challengeType]);

  const handleWatchExplanation = async () => {
    if (script) {
      setExpanded(true);
      return;
    }
    await loadScript();
  };

  const handlePlayPause = async () => {
    if (!script) {
      const loaded = await loadScript();
      if (!loaded) return;
    }

    if (playback.isPlaying) {
      playback.stop();
      return;
    }

    await playback.play();
  };

  useEffect(() => {
    return () => {
      cancelActiveTtsPlayback(true);
    };
  }, []);

  const showReadAlong = playback.isPlaying && highlightWhileReading && script;

  return (
    <div className="mt-4">
      <Button
        variant="ghost"
        onClick={handleWatchExplanation}
        disabled={isLoading}
        className="px-4 py-2 text-sm"
      >
        {isLoading ? '⏳ Generating…' : '🎙️ Hear the Explanation'}
      </Button>

      {error && (
        <p className="mt-2 font-body text-sm text-error">{error}</p>
      )}

      {expanded && script && (
        <div className="mt-4 bg-bg-surface rounded-xl border border-border-subtle shadow-card overflow-hidden">
          <div className="bg-bg-subtle px-4 py-3 border-b border-border-subtle flex items-center justify-between gap-3">
            <p className="font-display font-semibold text-sm text-text-primary">
              Solution Walkthrough
            </p>
            <button
              type="button"
              onClick={() => {
                if (playback.isPlaying || playback.isLoading) {
                  playback.stop();
                } else {
                  void handlePlayPause();
                }
              }}
              className="font-body text-sm font-semibold px-3 py-1.5 rounded-md bg-brand text-white hover:bg-brand-dark transition-colors"
            >
              {playback.isPlaying ? '⏹ Stop' : playback.isLoading ? '…' : '▶ Play'}
            </button>
          </div>

          <div className="p-4 space-y-2">
            {playback.isPlaying && highlightWhileReading ? (
              <ReadAlongSentences
                sentences={playback.bodySentences}
                activeIndex={playback.activeBodyIndex}
                interactive={Boolean(showReadAlong)}
                onSentenceClick={(index) => void playback.seekToBodyIndex(index)}
              />
            ) : (
              playback.bodySentences.map((sentence, i) => (
                <p
                  key={i}
                  className="font-body text-base text-text-primary leading-relaxed"
                >
                  {sentence}
                </p>
              ))
            )}
          </div>

          <p className="px-4 pb-4 font-body text-xs text-text-muted">
            Narration is generated by AI and read aloud with Deepgram text-to-speech.
          </p>
        </div>
      )}
    </div>
  );
}
