import Link from 'next/link';
import { Badge } from '@/components/ui/Badge';
import { Card } from '@/components/ui/Card';
import type { ChallengeCategory, ChallengeDifficulty } from '@/data/types';

export interface UserChallengeListItem {
  id: string;
  title: string;
  category: string;
  difficulty: string;
  concepts: string[];
  companyName: string | null;
  createdAt: string;
  attemptCount: number;
  hasPassed: boolean;
}

interface UserChallengeCardProps {
  challenge: UserChallengeListItem;
}

export function UserChallengeCard({ challenge }: UserChallengeCardProps) {
  const statusLabel = challenge.hasPassed
    ? '✓ Passed'
    : challenge.attemptCount > 0
      ? `${challenge.attemptCount} Attempt${challenge.attemptCount === 1 ? '' : 's'}`
      : 'Not Attempted';

  return (
    <Link href={`/my-challenges/${challenge.id}`}>
      <Card className="h-full transition-all duration-150 hover:shadow-raised hover:border-brand/30 cursor-pointer">
        <div className="flex items-start justify-between mb-3">
          <div className="flex gap-2 flex-wrap">
            <Badge type="category" value={challenge.category as ChallengeCategory} />
            <Badge type="difficulty" value={challenge.difficulty as ChallengeDifficulty} />
            <span className="text-xs font-body font-semibold px-2.5 py-1 rounded-sm bg-brand-light text-brand">
              Generated by you
            </span>
          </div>
        </div>

        <h3 className="font-display font-bold text-lg text-text-primary mb-2">
          {challenge.title}
        </h3>

        {challenge.companyName && (
          <p className="font-body text-sm text-text-secondary mb-2">
            From: {challenge.companyName}
          </p>
        )}

        <p className="font-body text-sm text-text-muted">{statusLabel}</p>
      </Card>
    </Link>
  );
}
